#!/bin/sh

set -e

if [ -z "$REBAR_DEPS_DIR" ]
then
        echo "rebar deps dir not set. can't fix up piqi_rpc app file." 1>&2
        exit 1
fi

VERSION=$(git describe --always --tags `git log -n 1 --pretty=format:%h .`)

sed  "s/vsn, git/vsn, \"${VERSION}\"/"  $REBAR_DEPS_DIR/piqi_src/piqi-rpc/src/piqi_rpc.app.src > ebin/piqi_rpc.app
