#!/bin/bash

set -e

if [ -n "`grep fake_module_piqi ebin/piqi_rpc.app`" ]; then
    # pass an empty file as config so that no hooks are executed on the second
    # recompile
    rebar compile --config "/dev/null" deps_dir=$REBAR_DEPS_DIR
fi
